Feat/add internal logs
lablabs/terraform-aws-eks-vector-agent-log pull request #18
Opened 2024-09-20 13:40 UTC by SolarMiroslav

# Description

Vector is not collecting internal_logs and sending those logs to LOKI endpoint. Therefore we want ability to instrument Vector to scrape internal_logs as well. Internal_logs are not exposing labels about pod/node/etc therefore it needs to be enriched using vector transform operation.

## Type of change

- [ ] A bug fix (PR prefix `fix`)
- [x] A new feature (PR prefix `feat`)
- [ ] A code change that neither fixes a bug nor adds a feature (PR prefix `refactor`)
- [ ] Adding missing tests or correcting existing tests (PR prefix `test`)
- [ ] Changes that do not affect the meaning of the code like white-spaces, formatting, missing semi-colons, etc. (PR prefix `style`)
- [ ] Changes to our CI configuration files and scripts (PR prefix `ci`)
- [ ] Documentation only changes (PR prefix `docs`)

## How Has This Been Tested?
Change was tested in LARA, by setting loki_internal_logs_enabled = false/true. Checked in grafana if logs are delivered to loki with correct labels. Checked if custom configs are not overwritten.

2024-09-30 19:56 UTC, jaygridley commented
Quick question here, would it be possible to sink the internal logs to the console (stdout), so the logs are enriched as other Pod logs?

2024-10-01 06:55 UTC, SolarMiroslav commented
@jaygridley already tried that using "console" source, but it is not working due to the fact that vector pod cannot scrape it self (idk probably due to some security reasons which could lead to some infinite loops).
<img width="1370" alt="image" src="https://github.com/user-attachments/assets/4c0008d7-abb0-47e2-a6ee-260600acf2f6">


_vector.dev/exclude: "true"_ in help chart is hardcoded and cannot be modified (even in the latest version). Therefore I had to use internal_logs source for this case with enrichment using "transform".

![CleanShot 2024-10-01 at 08 48 33@2x](https://github.com/user-attachments/assets/85cd132d-af4a-4e49-9474-dcf0faf6b622)

2024-10-01 18:29 UTC, jaygridley requested changes

2024-10-01 18:29 UTC, jaygridley commented on values.tf
> +        "filter_logs" : {
```suggestion
        "loki_internal_logs_severity_filter" : {
```

2024-10-01 18:29 UTC, jaygridley commented on values.tf
> +        "internal_logs_severity_map" = {
```suggestion
        "loki_internal_logs_severity_map" = {
```

2024-10-01 18:29 UTC, jaygridley commented on values.tf
> +        "enrich_internal_logs" = {
```suggestion
        "loki_internal_logs_enrichment" = {
```

2024-10-01 18:29 UTC, jaygridley commented on variables.tf
> +variable "loki_internal_logs_filter_log_level" {
```suggestion
variable "loki_internal_logs_severity" {
```

2024-10-01 18:29 UTC, jaygridley commented on variables.tf
> +  description = "Variable defining log level to be filtered before logs are send to Loki endpoint"
```suggestion
  description = "Internal log severity to be sent to Loki"
```

2024-10-01 18:29 UTC, jaygridley commented on variables.tf
> +  description = "Variable indicating whether Vector is scraping internal_logs"
```suggestion
  description = "Whether Vector internal logs should be sent to Loki"
```

2024-10-04 07:03 UTC, SolarMiroslav commented on values.tf
> +        "filter_logs" : {
Updated

2024-10-04 07:03 UTC, SolarMiroslav commented on values.tf
> +        "internal_logs_severity_map" = {
Updated

2024-10-04 07:03 UTC, SolarMiroslav commented on values.tf
> +        "enrich_internal_logs" = {
Updated

2024-10-04 07:04 UTC, SolarMiroslav commented on variables.tf
> +variable "loki_internal_logs_filter_log_level" {
Updated

2024-10-04 07:04 UTC, SolarMiroslav commented on variables.tf
> +  description = "Variable defining log level to be filtered before logs are send to Loki endpoint"
Updated

2024-10-04 07:04 UTC, SolarMiroslav commented on variables.tf
> +  description = "Variable indicating whether Vector is scraping internal_logs"
Updated

2024-10-21 11:05 UTC, jaygridley requested changes

2024-10-21 11:05 UTC, jaygridley commented on variables.tf
> +  description = "Internal log severity to be sent to Loki"
```suggestion
  description = "The severity of internal logs to be sent to Loki"
```

2024-10-24 08:28 UTC, jaygridley approved these changes
LGTM

2024-10-24 09:13 UTC, merged